#!/usr/bin/env bash

gcc-10 -flto -Werror=undef -Werror=implicit -Werror=return-type  -fno-common -g -O2 -I/home/sverker/src/otp2/erts/x86_64-pc-linux-gnu    -D_GNU_SOURCE  -DHAVE_CONFIG_H -Wall -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Wdeclaration-after-statement -DUSE_THREADS -D_THREAD_SAFE -D_REENTRANT -DPOSIX_THREADS -D_POSIX_THREAD_SAFE_FUNCTIONS  -DERLANG_GIT_VERSION="\"a900fff08a\"" -DBEAMASM=1 -Ix86_64-pc-linux-gnu/opt/jit -Ibeam -Isys/unix -Isys/common -Ix86_64-pc-linux-gnu -Izlib  -Ipcre -I../include -I../include/x86_64-pc-linux-gnu -I../include/internal -I../include/internal/x86_64-pc-linux-gnu -Ibeam/jit -Ibeam/jit/x86 -c erl_main.c -o erl_main.o
gcc-10 -flto -Werror=undef -Werror=implicit -Werror=return-type  -fno-common -g  -O3 -fomit-frame-pointer -I/home/sverker/src/otp2/erts/x86_64-pc-linux-gnu    -D_GNU_SOURCE  -DHAVE_CONFIG_H -Wall -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Wdeclaration-after-statement -DUSE_THREADS -D_THREAD_SAFE -D_REENTRANT -DPOSIX_THREADS -D_POSIX_THREAD_SAFE_FUNCTIONS  -DERLANG_GIT_VERSION="\"a900fff08a\"" -DBEAMASM=1 -Ix86_64-pc-linux-gnu/opt/jit -Ibeam -Isys/unix -Isys/common -Ix86_64-pc-linux-gnu -Izlib  -Ipcre -I../include -I../include/x86_64-pc-linux-gnu -I../include/internal -I../include/internal/x86_64-pc-linux-gnu -Ibeam/jit -Ibeam/jit/x86 -c erl_map.c -o erl_map.o
gcc-10 -flto -Werror=undef -Werror=implicit -Werror=return-type  -fno-common -g  -O3 -fomit-frame-pointer -I/home/sverker/src/otp2/erts/x86_64-pc-linux-gnu    -D_GNU_SOURCE  -DHAVE_CONFIG_H -Wall -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Wdeclaration-after-statement -DUSE_THREADS -D_THREAD_SAFE -D_REENTRANT -DPOSIX_THREADS -D_POSIX_THREAD_SAFE_FUNCTIONS  -DERLANG_GIT_VERSION="\"a900fff08a\"" -DBEAMASM=1 -Ix86_64-pc-linux-gnu/opt/jit -Ibeam -Isys/unix -Isys/common -Ix86_64-pc-linux-gnu -Izlib  -Ipcre -I../include -I../include/x86_64-pc-linux-gnu -I../include/internal -I../include/internal/x86_64-pc-linux-gnu -Ibeam/jit -Ibeam/jit/x86 -c utils.c -o utils.o
gcc-10 -flto -Werror=undef -Werror=implicit -Werror=return-type  -fno-common -g  -O3 -fomit-frame-pointer -I/home/sverker/src/otp2/erts/x86_64-pc-linux-gnu    -D_GNU_SOURCE  -DHAVE_CONFIG_H -Wall -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Wdeclaration-after-statement -DUSE_THREADS -D_THREAD_SAFE -D_REENTRANT -DPOSIX_THREADS -D_POSIX_THREAD_SAFE_FUNCTIONS  -DERLANG_GIT_VERSION="\"a900fff08a\"" -DBEAMASM=1 -Ix86_64-pc-linux-gnu/opt/jit -Ibeam -Isys/unix -Isys/common -Ix86_64-pc-linux-gnu -Izlib  -Ipcre -I../include -I../include/x86_64-pc-linux-gnu -I../include/internal -I../include/internal/x86_64-pc-linux-gnu -Ibeam/jit -Ibeam/jit/x86 -c erl_debug.c -o erl_debug.o


echo MY LINKING
g++-10 -o exe \
       -Wl,-export-dynamic erl_main.o \
       erl_map.o \
       utils.o \
       erl_debug.o
       
